Remove dependencies to fiddle and fiddley
Because clipboard-2.0.0 doesn't work with fiddley:

```
NoMethodError: undefined method 'null?' for an instance of Fiddley::MemoryPointer
C:/Ruby34-x64/lib/ruby/gems/3.4.0/gems/clipboard-2.0.0/lib/clipboard/windows.rb:58:in 'C
lipboard::Windows#paste'
```

Windows users should install ffi instead if they want clipboard commands.